// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Service.Persistence.Contexts;

namespace Project.Service.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20190630151922_guid_")]
    partial class guid_
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Project.Service.Models.VehicleMake", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.HasKey("Id");

                    b.ToTable("VehicleMakes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ca5ebe0-9b49-11e9-b475-0800200c9a66"),
                            Abrv = "VW",
                            Name = "VolksWagen"
                        },
                        new
                        {
                            Id = new Guid("0d6ac610-9b49-11e9-b475-0800200c9a66"),
                            Abrv = "BMW",
                            Name = "Bmw"
                        });
                });

            modelBuilder.Entity("Project.Service.Models.VehicleModel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abrv")
                        .IsRequired()
                        .HasMaxLength(15);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(35);

                    b.Property<Guid>("VehicleMakeId");

                    b.HasKey("Id");

                    b.HasIndex("VehicleMakeId");

                    b.ToTable("VehicleModels");

                    b.HasData(
                        new
                        {
                            Id = new Guid("967853e0-3946-444f-a2d1-0d5765fa5745"),
                            Abrv = "G3",
                            Name = "Golf 3",
                            VehicleMakeId = new Guid("2ca5ebe0-9b49-11e9-b475-0800200c9a66")
                        },
                        new
                        {
                            Id = new Guid("d42f2e63-17ca-4184-b5f9-1026ecf323bd"),
                            Abrv = "X3",
                            Name = "x3",
                            VehicleMakeId = new Guid("0d6ac610-9b49-11e9-b475-0800200c9a66")
                        });
                });

            modelBuilder.Entity("Project.Service.Models.VehicleModel", b =>
                {
                    b.HasOne("Project.Service.Models.VehicleMake", "VehicleMake")
                        .WithMany("VehicleModels")
                        .HasForeignKey("VehicleMakeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
